🐝 fix: build script should fail at first error

diff --git a/scripts/build-deploy-skins b/scripts/build-deploy-skins
--- a/scripts/build-deploy-skins
+++ b/scripts/build-deploy-skins
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Fails at first error
+set -e
+
 echo "Building vanilla"
 yarn run build
 yarn run build:services
